version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:
      - echo "Checking Docker version..."
      - docker --version
  build:
    commands:
      - echo "Building Docker image for Nginx app"
      - docker build -t simple-nginx-app:latest .
  post_build:
    commands:
      - echo "Build completed successfully at $(date)"
artifacts:
  files:
    - index.html
    - simple-nginx-deployment.yaml
    - simple-nginx-service.yaml
