version: 0.2
phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building Docker image for Nginx app"
      - docker build -t simple-nginx-app:latest .
  post_build:
    commands:
      - echo "Build completed successfully at $(date)"
artifacts:
  files:
    - index.html
    - simple-nginx-deployment.yaml
    - simple-nginx-service.yaml
